-- 0035_cashier_admissions.sql
--
-- Cashier admissions runtime (Jira RT-113 BC2).
-- [GATED] migration — owner-authorized on RT-113 (comment 10832); decisions
-- accepted as the basis in comment 10826.
--
-- Source-of-truth decisions:
--   - RT-113 comment 10763 (D2 server authority: one live admission per
--     (tenant, store, user); D8 the server's live admission wins, server
--     arrival order decides; D9 takeover; §3 server TTL)
--   - RT-113 comment 10826 (heartbeat renews the TTL with the SAME
--     admission_id; serialisation per (tenant, store, user) with exactly one
--     winner; same-key replay only while the admission is live; takeover
--     rate-limited per device)
--   - packages/contracts/openapi/pos-cashier-admissions.openapi.yaml
--
-- Changes, in order:
--   1. cashier_admissions — one row per admission. A row is LIVE while
--      ended_at IS NULL. The partial UNIQUE index uq_cashier_admissions_live
--      enforces "at most one live admission per (tenant, store, user)" in the
--      database; the service additionally serialises each (tenant, store,
--      user) with a transaction-scoped advisory lock and ends an expired live
--      row (end_reason 'expired') lazily, in the same transaction, before it
--      decides. A renewal (heartbeat) moves renewed_at / expires_at on the
--      SAME row, so the admission_id is stable. A takeover ends the other
--      device's row (end_reason 'takeover') and inserts a new row whose
--      takeover_of names the prior admission.
--   2. cashier_admission_requests — the idempotency store for
--      posCreateCashierAdmission, keyed on (tenant, device, sha256(key)). It
--      holds the request fingerprint (sha256 of the canonical body), the
--      admission the request produced and the 200 body to replay. Only
--      `admitted` outcomes are recorded (contract: "Only 200 outcomes are
--      recorded"; `active_elsewhere` recorded nothing). expires_at bounds the
--      replay window to the admission TTL applied at the time. The raw key is
--      never stored.
--
-- Cross-row references (takeover_of, a replay entry's admission_id) are
-- composite FKs on (tenant_id, id), so they cannot cross tenants. device_id
-- stays a single-column FK to devices(id) — a composite one would need a new
-- UNIQUE on the existing devices table (the sales.device_id precedent, 0033);
-- the service always takes the device, tenant and store from one devices row.
--
-- Both tables are tenant-RLS-forced. cashier_admissions has SELECT, INSERT
-- and UPDATE policies and no DELETE policy: rows are ended, never removed.
-- cashier_admission_requests is a replay cache, so it also has a DELETE
-- policy for the service's purge of a device's expired entries.
--
-- ---------------------------------------------------------------------------
-- DATA-LIFECYCLE CLASSIFICATION (SI-012 / §XIV)
-- ---------------------------------------------------------------------------
-- cashier_admissions is OPERATIONAL-CLASS security state. It holds
-- identifiers only (tenant, store, user, device, admission) and timestamps;
-- offline_admitted_at is the terminal's claimed local time, provenance only.
-- No PIN, PIN hash, grant body, token or secret is stored (D2, AD-2). The
-- display name is resolved from users at response time and is not copied.
-- cashier_admission_requests holds two SHA-256 digests, an admission id and
-- the replayable `admitted` body, whose only personal datum is the cashier's
-- display_name (already disclosed to that device by the same response). Its
-- rows are expired after at most one admission TTL and purged per device.
--
-- Lock duration: two new tables; only catalog locks plus SHARE ROW EXCLUSIVE
-- on the referenced tenants, stores, users and devices while the FKs are
-- created (brief, no row scan — both tables are empty).
-- Grants: none here — production grants the domain role SELECT, INSERT and
-- UPDATE on cashier_admissions and SELECT, INSERT, UPDATE and DELETE on
-- cashier_admission_requests outside migrations (see 0006 / the RT-113 BC2
-- PR). The auth lookup role needs no grant on either table.
-- Reversible via 0035_cashier_admissions.down.sql.

BEGIN;

-- =============================================================================
-- 1. cashier_admissions — the server's cashier admission authority (D2)
-- =============================================================================

CREATE TABLE cashier_admissions (
  -- admission_id; UUIDv7 generated by the service.
  id                  UUID        PRIMARY KEY,
  tenant_id           UUID        NOT NULL REFERENCES tenants(id) ON DELETE RESTRICT,
  -- Wire `branch_id`; always the authenticated device's store.
  store_id            UUID        NOT NULL,
  user_id             UUID        NOT NULL REFERENCES users(id)   ON DELETE RESTRICT,
  device_id           UUID        NOT NULL REFERENCES devices(id) ON DELETE RESTRICT,
  mode                TEXT        NOT NULL,
  -- The terminal's local time of an offline admission (D8). Provenance for
  -- audit only; never authority.
  offline_admitted_at TIMESTAMPTZ,
  -- The prior admission this one replaced by takeover (D9); same tenant
  -- (composite FK below).
  takeover_of         UUID,
  created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
  -- Last time the admission was granted or renewed (the response's
  -- server_time).
  renewed_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
  expires_at          TIMESTAMPTZ NOT NULL,
  ended_at            TIMESTAMPTZ,
  end_reason          TEXT,
  -- Target of the tenant-qualified composite FKs below.
  CONSTRAINT uq_cashier_admissions_tenant_id UNIQUE (tenant_id, id),
  CONSTRAINT fk_cashier_admissions_store_tenant
    FOREIGN KEY (tenant_id, store_id) REFERENCES stores (tenant_id, id) ON DELETE RESTRICT,
  -- A takeover can only name a prior admission of the same tenant.
  CONSTRAINT fk_cashier_admissions_takeover_of_tenant
    FOREIGN KEY (tenant_id, takeover_of) REFERENCES cashier_admissions (tenant_id, id) ON DELETE RESTRICT,
  CONSTRAINT cashier_admissions_mode_valid
    CHECK (mode IN ('online', 'reconcile_offline')),
  CONSTRAINT cashier_admissions_offline_time_reconcile_only
    CHECK (offline_admitted_at IS NULL OR mode = 'reconcile_offline'),
  CONSTRAINT cashier_admissions_end_reason_valid
    CHECK (end_reason IS NULL OR end_reason IN ('device_end', 'takeover', 'expired')),
  CONSTRAINT cashier_admissions_ended_has_reason
    CHECK ((ended_at IS NULL) = (end_reason IS NULL)),
  CONSTRAINT cashier_admissions_window_valid
    CHECK (renewed_at >= created_at AND expires_at > renewed_at),
  CONSTRAINT cashier_admissions_takeover_not_self
    CHECK (takeover_of IS NULL OR takeover_of <> id)
);

-- The single-active rule (D2): at most ONE live admission per
-- (tenant, store, user). A second live INSERT fails with 23505.
CREATE UNIQUE INDEX uq_cashier_admissions_live
  ON cashier_admissions (tenant_id, store_id, user_id)
  WHERE ended_at IS NULL;

CREATE INDEX idx_cashier_admissions_device_live
  ON cashier_admissions (tenant_id, device_id)
  WHERE ended_at IS NULL;

ALTER TABLE cashier_admissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE cashier_admissions FORCE ROW LEVEL SECURITY;

CREATE POLICY cashier_admissions_tenant_select ON cashier_admissions
  FOR SELECT USING (tenant_id = CASE
      WHEN current_setting('app.current_tenant', true) = '' THEN NULL
      ELSE current_setting('app.current_tenant', true)::uuid END);
CREATE POLICY cashier_admissions_tenant_insert ON cashier_admissions
  FOR INSERT WITH CHECK (tenant_id = CASE
      WHEN current_setting('app.current_tenant', true) = '' THEN NULL
      ELSE current_setting('app.current_tenant', true)::uuid END);
CREATE POLICY cashier_admissions_tenant_update ON cashier_admissions
  FOR UPDATE USING (tenant_id = CASE
      WHEN current_setting('app.current_tenant', true) = '' THEN NULL
      ELSE current_setting('app.current_tenant', true)::uuid END)
  WITH CHECK (tenant_id = CASE
      WHEN current_setting('app.current_tenant', true) = '' THEN NULL
      ELSE current_setting('app.current_tenant', true)::uuid END);

-- =============================================================================
-- 2. cashier_admission_requests — idempotency store (Constitution §XI)
-- =============================================================================

CREATE TABLE cashier_admission_requests (
  id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id       UUID        NOT NULL REFERENCES tenants(id) ON DELETE RESTRICT,
  -- The key is scoped to the authenticated device (contract).
  device_id       UUID        NOT NULL REFERENCES devices(id) ON DELETE RESTRICT,
  -- sha256(idempotency_key); the raw key is never stored.
  key_hash        BYTEA       NOT NULL,
  -- sha256 of the canonical request body.
  request_hash    BYTEA       NOT NULL,
  -- Same tenant as the entry (composite FK below).
  admission_id    UUID        NOT NULL,
  -- The original `admitted` 200 body, replayed verbatim.
  response_body   JSONB       NOT NULL,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  expires_at      TIMESTAMPTZ NOT NULL,
  CONSTRAINT uq_cashier_admission_requests_key UNIQUE (tenant_id, device_id, key_hash),
  CONSTRAINT fk_cashier_admission_requests_admission_tenant
    FOREIGN KEY (tenant_id, admission_id) REFERENCES cashier_admissions (tenant_id, id) ON DELETE RESTRICT,
  CONSTRAINT cashier_admission_requests_key_hash_len CHECK (octet_length(key_hash) = 32),
  CONSTRAINT cashier_admission_requests_request_hash_len CHECK (octet_length(request_hash) = 32),
  CONSTRAINT cashier_admission_requests_window_valid CHECK (expires_at > created_at)
);

CREATE INDEX idx_cashier_admission_requests_admission
  ON cashier_admission_requests (admission_id);

ALTER TABLE cashier_admission_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE cashier_admission_requests FORCE ROW LEVEL SECURITY;

CREATE POLICY cashier_admission_requests_tenant_select ON cashier_admission_requests
  FOR SELECT USING (tenant_id = CASE
      WHEN current_setting('app.current_tenant', true) = '' THEN NULL
      ELSE current_setting('app.current_tenant', true)::uuid END);
CREATE POLICY cashier_admission_requests_tenant_insert ON cashier_admission_requests
  FOR INSERT WITH CHECK (tenant_id = CASE
      WHEN current_setting('app.current_tenant', true) = '' THEN NULL
      ELSE current_setting('app.current_tenant', true)::uuid END);
CREATE POLICY cashier_admission_requests_tenant_update ON cashier_admission_requests
  FOR UPDATE USING (tenant_id = CASE
      WHEN current_setting('app.current_tenant', true) = '' THEN NULL
      ELSE current_setting('app.current_tenant', true)::uuid END)
  WITH CHECK (tenant_id = CASE
      WHEN current_setting('app.current_tenant', true) = '' THEN NULL
      ELSE current_setting('app.current_tenant', true)::uuid END);
CREATE POLICY cashier_admission_requests_tenant_delete ON cashier_admission_requests
  FOR DELETE USING (tenant_id = CASE
      WHEN current_setting('app.current_tenant', true) = '' THEN NULL
      ELSE current_setting('app.current_tenant', true)::uuid END);

COMMIT;
